export const SLOT_STATUS = {
  AVAILABLE: "AVAILABLE",
  BOOKED: "BOOKED",
  BREAK: "BREAK",
};

export const SLOT_REASON = {
  BOOKED: "BOOKED",
  BREAK: "BREAK",
  DOCTOR_ON_LEAVE: "DOCTOR_ON_LEAVE",
  DOCTOR_UNAVAILABLE: "DOCTOR_UNAVAILABLE",
  NO_SCHEDULE: "NO_SCHEDULE",
  WORKING_HOURS_NOT_SET: "WORKING_HOURS_NOT_SET",
};
